# Generated by Django 5.2.1 on 2025-06-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
